version: '3'
services:
 server:
  network_mode: host
  build: ./server/
  ports:
  - "8443:8443"
  - "8080:8080"
  env_file:
  - ./server/startup.env
  volumes:
  - ./server/certs/:/var/certs/:ro
  entrypoint: ./startup_server.sh
  depends_on:
  - redis

 redis:
  image: redis
  command: redis-server /usr/local/etc/redis/redis.conf
  volumes:
  - ./server/Redis/data/:/data
  - ./server/Redis/log/:/data/log
  - ./server/Redis/redis.conf:/usr/local/etc/redis/redis.conf
  expose: 
  - 6379
  ports:
  - "6379:6379"

 frontend:
    build: ./frontend/
    volumes:
      - ./frontend/src/:/usr/src/app
      - ./frontend/src//usr/src/app/node_modules
    ports:
      - '4200:80'
