version: '3'
services:
        server:
                build: .
                ports:
                - "8443:8443"
                - "8080:8080"
                env_file:
                - ./startup.env
                volumes:
                - ./certs/:/var/certs/:ro

