version: '3'
services:
        server:
                image: 'michalmonko/table_footballserver'
                build: .
                ports:
                - "8443:8443"
                - "8080:8080"
                env_file:
                - ./startup.env
                volumes:
                - ./certs/server/:/var/certs/:ro

